$(document).ready(function(){
  let space_cadet = new Board()
  space_cadet.render()
  let dog = new Dog()
  dog.render()
  dog.moveDog()
  let asteroid = new Asteroid()
  asteroid.render()
  asteroid.moveAsteroids()
})
