$(document).ready(function(){
  let board = new Board()
  board.render()
  board.startGame()
  let dog = new Dog()
  dog.render()
  dog.moveDog()
  board.win()
  board.collided()
  //board.endGame()
  //rock.endGame()
})
